### ISSUE TITLE
Performance against TitaNet-L

### ISSUE THREAD

**Issue by Oscaarjs** [IDRnD/ReDimNet#15]
Amazing work!

Looking forward for the updated release that's trained on even more data.

In the paper I can see that you've tested it against a lot of different models. However, have you tested it against Nvidias TitaNet-L?  ([https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/titanet_large](url))

Would be interesting as a comparison :)

Best

**Comment by vanIvan** [comment]
Thank you! We are going to release new models soon, this or next week.

As for the comparison with TitaNet-L, it’s a bit unfortunate that the authors didn’t test on vox1-test E/H protocols or other sets like SITW/VOICEs, as it would have made direct comparisons much easier.

**Comment by vanIvan** [comment]
@Oscaarjs happy to share good news, we have released first models pretrained on `voxblink2`, you could find them on [evaluation](https://github.com/IDRnD/ReDimNet/blob/master/EVALUATION.md) page. The first example there is with the best voxblink2 finetuned model.

**Comment by Oscaarjs** [comment]
@vanIvan Thanks a lot! 

Already tested the "M" model a bit on a small-scale custom dataset and its significantly better than TitaNet-L, great job guys!

This however of course makes me curios to whether you have any plans of releasing the larger model any time soon as well?

Best

**Comment by vanIvan** [comment]
@Oscaarjs great, thanks for testing! Is it your internal dataset or something publicly available? Probably you can share only metrics for few of models, say if you tested our initial b6 with new M model and with Titanet-L - would be really helpful to estimate performance on OOF data. 

Regarding releasing larger model, we are currently pretraining 12M larger model on 250k+ identities (voxblink2 + our internal YouTube based research dataset), after consulting with our stakeholders we might release it under non-commercial license.

**Comment by Oscaarjs** [comment]
@vanIvan It was a very small internal dataset. Only did some small testing, where I had a bunch of "postitive" examples as in same person talking against a set of "negative" examples (other people talking) and I compared the distributions of the cosine similarities between these. As can be seen its clear that the ResDimNet is significantly better at separating the voices (Ignore the similarities of 1.0, I was lazy and didn't remove the trace of the similarity matrix).

Cool with an even better model potentially! Unfortunate, but understandable, with a non-commercial license though :)

![resdimnet](https://github.com/user-attachments/assets/82bc8619-40f7-4538-b337-64eec3960d0b)
![titanet](https://github.com/user-attachments/assets/680fa19b-e87c-463a-981f-5f231d22eccf)

**Comment by vanIvan** [comment]
@Oscaarjs thanks for sharing! 

> Unfortunate, but understandable, with a non-commercial license though :)

Well, the model inherits the license of dataset, it's pity, it's true
