### ISSUE TITLE
Question: Proper Method for Loading Audio Files into Model

### ISSUE THREAD

**Issue by mnicnc404** [IDRnD/ReDimNet#7]
Hi,

I would like to know the proper way to use your model. Can I directly input a signal loaded with torchaudio.load into your model as shown below?

```python
import torch
import torchaudio 

model = torch.hub.load('IDRnD/ReDimNet', 'b0', pretrained=True, finetuned=True).eval()
signal, fs = torchaudio.load("audio.wav")
out = model(signal)
```
Or is there a recommended method for loading audio files for your model?

Thank you for your help!

**Comment by vanIvan** [comment]
I suppose it should work this way, the input tensor size for model should be: `[batch_size, num_samples]`, I assume `torch.load` with default arguments should return tensor of shape `[1, num_samples]` which should work

**Comment by m-mandel** [comment]
Hey! Thank you for your work!

I wanted to point out that the code fails when running with batch_size == 1:

File ~/.cache/torch/hub/IDRnD_ReDimNet_master/redimnet.py:955, in ReDimNetWrap.forward(self, x)
    [953]../.cache/torch/hub/IDRnD_ReDimNet_master/redimnet.py:953) x = self.spec(x).unsqueeze(1)
    [954].../.cache/torch/hub/IDRnD_ReDimNet_master/redimnet.py:954) out = self.backbone(x)
--> [955].../~/.cache/torch/hub/IDRnD_ReDimNet_master/redimnet.py:955) out = self.bn(self.pool(out))
    [956].../~/.cache/torch/hub/IDRnD_ReDimNet_master/redimnet.py:956) out = self.linear(out)
    [957].../~/.cache/torch/hub/IDRnD_ReDimNet_master/redimnet.py:957) if self.emb_bn:

...
...
...

File /usr/local/lib/python3.10/dist-packages/torch/nn/functional.py:2448, in _verify_batch_size(size)
   [2446].../torch/nn/functional.py:2446)     size_prods *= size[i + 2]
   [2447].../torch/nn/functional.py:2447) if size_prods == 1:
-> [2448].../torch/nn/functional.py:2448)     raise ValueError(f"Expected more than 1 value per channel when training, got input size {size}")

ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 4608])

**Comment by vanIvan** [comment]
@m-mandel could you please do `model.eval()` before inferencing it.

**Comment by m-mandel** [comment]
Oh, right! works perfectly now.
Enjoy the conference :)
